"""M1: initial schema

Revision ID: 205a64dde915
Revises: 
Create Date: 2026-07-16 22:13:51.798467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '205a64dde915'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ASSAULT', 'SNIPER', 'SUPPORT', 'DMR', 'SCOUT', name='role', native_enum=False, length=32), nullable=True),
    sa.Column('drive_type', sa.Enum('AEG', 'GBB', 'SPRING', 'HPA', name='drivetype', native_enum=False, length=32), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experiencelevel', native_enum=False, length=32), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='kitstatus', native_enum=False, length=32), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_slug'), 'kits', ['slug'], unique=True)
    op.create_index(op.f('ix_kits_status'), 'kits', ['status'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_code'), 'shops', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('match_key', sa.String(length=512), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_match_key'), 'products', ['match_key'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # GIN-индекс по JSONB-атрибутам для фильтров по характеристикам товара
    op.create_index(
        'ix_products_attrs_gin', 'products', ['attrs'], unique=False, postgresql_using='gin'
    )
    op.create_table('kit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('FIXED', 'FLEXIBLE', name='kititemtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('attr_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(item_type = 'fixed' AND product_id IS NOT NULL) OR (item_type = 'flexible' AND category_id IS NOT NULL)", name='ck_kit_items_type_target'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_items_kit_id'), 'kit_items', ['kit_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('raw_title', sa.String(length=512), nullable=False),
    sa.Column('raw_category', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'external_id', name='uq_offers_shop_external')
    )
    op.create_index(op.f('ix_offers_product_id'), 'offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_offers_shop_id'), 'offers', ['shop_id'], unique=False)
    op.create_table('kit_item_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kit_item_id'], ['kit_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_item_id', 'product_id', name='uq_candidate_item_product')
    )
    op.create_index(op.f('ix_kit_item_candidates_kit_item_id'), 'kit_item_candidates', ['kit_item_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_offer_id'), 'price_history', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_offer_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_kit_item_candidates_kit_item_id'), table_name='kit_item_candidates')
    op.drop_table('kit_item_candidates')
    op.drop_index(op.f('ix_offers_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_kit_items_kit_id'), table_name='kit_items')
    op.drop_table('kit_items')
    op.drop_index('ix_products_attrs_gin', table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_match_key'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_shops_code'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_kits_status'), table_name='kits')
    op.drop_index(op.f('ix_kits_slug'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
